# Generated by Django 4.2.4 on 2023-11-12 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("email", models.CharField(max_length=128)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("SELLER", "Seller"),
                            ("CUSTOMER", "Customer"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=8,
                    ),
                ),
                ("balance", models.PositiveIntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
