# Generated by Django 4.2.4 on 2023-11-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.JSONField(default=dict),
        ),
    ]
