# Generated by Django 4.2.4 on 2023-11-19 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_cart_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposithistory",
            name="customer",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
            ),
            preserve_default=False,
        ),
    ]
