# Generated by Django 4.2.4 on 2023-11-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellingproduct",
            name="is_available",
        ),
        migrations.AddField(
            model_name="sellingproduct",
            name="stock_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
