# Generated by Django 4.2.4 on 2023-11-13 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0001_initial"),
        ("shop", "0002_remove_sellingproduct_is_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellingproduct",
            name="color_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="shop.colorvariant"
            ),
        ),
        migrations.AlterField(
            model_name="sellingproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="shop.product"
            ),
        ),
        migrations.AlterField(
            model_name="sellingproduct",
            name="properties_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shop.propertiesvariant",
            ),
        ),
        migrations.AlterField(
            model_name="sellingproduct",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="seller.seller"
            ),
        ),
        migrations.AlterField(
            model_name="sellingproduct",
            name="size_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="shop.sizevariant"
            ),
        ),
    ]
